feat(automation): new world doc pr creation
algolia/cli pull request #130
Opened 2023-09-29 15:59 UTC by loicsay

2023-10-03 09:39 UTC, loicsay commented
@dylantientcheu @clemfromspace 
I'm not sure about how we should handle the `runInCommand` property for each example 🤔 
Do you have any idea? Should we hardcode a list of commands that allow this feature in the CLI codebase?

2023-10-03 09:49 UTC, dylantientcheu commented
For now we can edit the submitted PR each time, i'd prefer not to bloat the cli code.

2023-10-03 14:15 UTC, clemfromspace commented
I think we should run the example directly, so we will have to edit the example to make them match what indices / things we have in the doc. That way, no editing is necessary and it's more coherent maybe. WDYT?

2023-10-04 09:08 UTC, loicsay commented
@clemfromspace I agree, let's remove all `Examples` formatting for now and do it in `new-world-doc` 👍 
Same for the WebCLI I think? You're suggesting doing outside of this repo if I understand correctly?

2023-10-06 09:28 UTC, clemfromspace requested changes
Good job, the template way was definitely the way to go 👍 

I think we need to work more of the example presentation (splitting, etc.)
I also added some comments regarding the duplicated code / now shared code between the two docs generation methods.

2023-10-06 09:28 UTC, clemfromspace commented on internal/docs/yaml.go
> +	Slug        string
Some of these things are shared between `yaml` and `mdx`, what do you think about creating a `docs.go` file for the shared structs & functions?

2023-10-06 09:28 UTC, clemfromspace commented on internal/docs/mdx.go
> +		tpl, err := template.ParseFiles("internal/docs/mdx.tpl")
This should be outside of the loop.

2023-10-06 09:28 UTC, clemfromspace commented on internal/docs/mdx.tpl
> +{{ .Examples }}
In this case, the examples won't even be wrapped between backticks?
For the new docs, I would also split the examples so we can more easily copy them / run them in the webcli.
Adding a new method to the `Command` struct like that:
```go
type Example struct {
	Desc   string
	Code   string
	WebCLI string
}

func (cmd Command) ExamplesList() []Example {
	var examples []Example
	examplesRaw := strings.Split(cmd.Examples, "#")
	for _, example := range examplesRaw {
		example = strings.TrimSpace(example)
		if len(example) == 0 {
			continue
		}
		exampleLines := strings.Split(example, "\n")

		code := strings.ReplaceAll(exampleLines[1], "$", "")
		code = strings.TrimSpace(code)

		examples = append(examples, Example{
			Desc: strings.Replace(exampleLines[0], "#", "", 1),
			Code: code,
		})

		// TODO: Add WebCLI example depending of:
		// 1. The presence of the `runInWebCLI` annotation on the command
		// 2. The presence of any piping or file flags in the example
	}
	return examples
}
```

WDYT?

2023-10-06 09:28 UTC, clemfromspace commented on internal/docs/mdx.go
> +func GenMdxFile(cmd *cobra.Command, dir string) error {
Could we keep a consistent naming between the `yaml` and `mdx` version?
```suggestion
func GenMdxTree(cmd *cobra.Command, dir string) error {
```

2023-10-06 09:28 UTC, clemfromspace commented on internal/docs/mdx.go
> +	for _, c := range cmd.Commands() {
Could we build the tree of the commands at the same place between the two version? Many of those lines are duplicated.

Maybe in the `docs.go`, adding a `getCommands` like
```go
func getCommands(cmd *cobra.Command) []Command {
	var commands []Command
	for _, c := range cmd.Commands() {
		if c.Hidden || c.Name() == "help" {
			continue
		}
		command := newCommand(c)
		if c.HasAvailableSubCommands() {
			for _, sub := range c.Commands() {
				command.SubCommands = append(command.SubCommands, newCommand(sub))
			}
		}
		commands = append(commands, command)
	}

	return commands
}
```

2023-10-06 10:00 UTC, clemfromspace commented
@loicsay I saw that you actually removed the example splitting, this was not what I wanted to say 😓 
Sorry about the confusion, I wanted to say that we should directly run the examples in the webCLI (for the available commands), but that we should edit those examples, directly in the CLI, to match the indices names & co that are present in the docs. This should be done maybe in a second step, along with adding a `availableInWebCLI` annotation on the commands.

2023-10-09 13:52 UTC, loicsay commented
Summary of our discussion with @clemfromspace:

- We'll add annotation (`runInWebCli`) to commands with `web CLI` enabled in `new-world-docs`
- Because there's differences between CLI examples and the ones run with the `web CLI`, we'll standardize all examples with the `new-world-docs`/`webCLI` (in a future PR)
- Examples with output or pipe symbols will automatically be non-runnable

2023-10-09 13:54 UTC, loicsay commented on pkg/cmd/indices/list/list.go
> +		Annotations: map[string]string{
Only added this one and `search.go` for testing, will add it to all other commands that can be run with the web CLI with the second PR that'll take care of standardize examples

2023-10-10 09:39 UTC, clemfromspace approved these changes
Love it, LGTM 🚀

2023-10-10 12:44 UTC, merged