chore: rename branch master to main
algolia/cli pull request #67
Opened 2022-10-03 16:01 UTC by loicsay

**⚠️ Merge this PR after changing `master` branch name to `main`**
[Guidelines here](https://github.com/github/renaming)

2022-10-03 16:02 UTC, loicsay commented on Makefile
> +VERSION := main
Not sure about that @clemfromspace 
What's the impact of changing the version name?

2022-10-05 09:03 UTC, loicsay commented on Makefile
> +VERSION := main
I didn't find any in the codebase 🤔 (but found an oversight in the Makefile)

2022-10-05 13:47 UTC, clemfromspace requested changes
One comment :)

2022-10-05 13:47 UTC, clemfromspace commented on Makefile
> +	git -C docs checkout main
This is for the documentation repo, AFAIK they still are on the `master` branch.

2022-10-05 15:30 UTC, merged