feat/objects operations
algolia/cli pull request #92
Opened 2022-12-13 11:07 UTC by loicsay

- feat: algolia objects operations
- fixup! feat: algolia objects operations
- fixup! fixup! feat: algolia objects operations

2022-12-20 08:33 UTC, clemfromspace requested changes
First pass done, good job 👍

2022-12-20 08:33 UTC, clemfromspace commented on pkg/cmd/objects/operations/operations.go
> +		ValidArgsFunction: cmdutil.IndexNames(opts.SearchClient),
I don't think you need a `ValidArgsFunction` since this command do not accept any args.

2022-12-20 08:33 UTC, clemfromspace commented on pkg/cmd/objects/operations/operations.go
> +		Short:             "Batch multiple different indexing operations",
```suggestion
		Short:             "Perform several indexing operations",
```

2022-12-20 08:33 UTC, clemfromspace commented on pkg/cmd/objects/operations/operations.go
> +			Batch multiple different indexing operations
```suggestion
			Perform several indexing operations defined in a file.
```

2022-12-20 08:33 UTC, clemfromspace commented on pkg/cmd/objects/operations/operations.go
> +			The file must contains one single JSON object per line (newline delimited JSON objects - ndjson format: https://ndjson.org/).
```suggestion
			The file must contains one single JSON object per line (newline delimited JSON objects - ndjson format: https://ndjson.org/).
			Each JSON object must be a valid indexing operation, as documented in the REST API documentation: https://www.algolia.com/doc/rest-api/search/#batch-write-operations-multiple-indices
```

2022-12-20 08:33 UTC, clemfromspace commented on pkg/cmd/objects/operations/operations.go
> +			#  Batch operations from the "operations.ndjson" file
```suggestion
			# Batch operations from the "operations.ndjson" file
```

2022-12-20 08:33 UTC, clemfromspace commented on pkg/cmd/objects/operations/operations.go
> +	cmd.Flags().StringVarP(&opts.File, "file", "F", "", "Read batch operation from `file` (use \"-\" to read from standard input)")
```suggestion
	cmd.Flags().StringVarP(&opts.File, "file", "F", "", "The file to read the indexing operations from (use \"-\" to read from standard input)")
```

2022-12-20 08:33 UTC, clemfromspace commented on pkg/cmd/objects/operations/operations.go
> +	cmd.Flags().BoolVarP(&opts.Wait, "wait", "w", false, "Wait for the operation to complete before returning")
```suggestion
	cmd.Flags().BoolVarP(&opts.Wait, "wait", "w", false, "Wait for the indexing operation(s) to complete before returning.")
```

2022-12-20 08:33 UTC, clemfromspace commented on pkg/cmd/objects/operations/operations.go
> +		opts.IO.UpdateProgressIndicatorLabel("Waiting for operation to complete")
```suggestion
		opts.IO.UpdateProgressIndicatorLabel("Waiting for the operations to complete")
```

2022-12-26 14:29 UTC, loicsay commented
Thanks @clemfromspace, way better 🙏

2023-01-10 06:48 UTC, clemfromspace approved these changes
One file comited by mistakes, feel free to merge afterwards 👍

2023-01-10 06:48 UTC, clemfromspace commented on test_operations.ndjson
> +{"action":"addObject","indexName":"index1","body":{"firstname":"Jimmie","lastname":"Barninger"}}
I guess this file was comited by mistake?

2023-01-10 10:02 UTC, merged